# Generated by Django 2.0.3 on 2018-03-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackmores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Au31581',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_31581',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au31587',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_31587',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au52039',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_52039',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au52040',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_52040',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au52043',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_52043',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au52044',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_52044',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au52658',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_52658',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au55511',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_55511',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au56439',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_56439',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au56715',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_56715',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au56888',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_56888',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au57048',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_57048',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au57049',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_57049',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au58108',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_58108',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au58346',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_58346',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au58347',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_58347',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au58348',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_58348',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au58504',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_58504',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au59769',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_59769',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au59771',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_59771',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au59772',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_59772',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au59774',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_59774',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au60196',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_60196',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au61713',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_61713',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au61714',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_61714',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au63080',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_63080',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au63081',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_63081',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au63125',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_63125',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au63126',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_63126',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au63243',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_63243',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au63448',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_63448',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au63582',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_63582',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au64872',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_64872',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au65702',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_65702',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au66044',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_66044',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au66393',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_66393',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au66394',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_66394',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au66485',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_66485',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au66521',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_66521',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au66537',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_66537',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au66551',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_66551',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au66552',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_66552',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au66553',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_66553',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au67489',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_67489',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au67490',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_67490',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au67491',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_67491',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au67492',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_67492',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au67493',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_67493',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au67494',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_67494',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au67495',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_67495',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au67497',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_67497',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au67499',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_67499',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au67606',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_67606',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au67966',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_67966',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au67970',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_67970',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au69162',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_69162',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au69163',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_69163',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au70153',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_70153',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au70258',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_70258',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au70259',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_70259',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au70260',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_70260',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au71529',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_71529',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au71530',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_71530',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au71933',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_71933',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au71934',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_71934',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au71935',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_71935',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au71941',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_71941',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au71942',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_71942',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au71946',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_71946',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au71947',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_71947',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au72686',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_72686',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au73681',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_73681',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au73682',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_73682',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au73685',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_73685',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au74651',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_74651',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au74931',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_74931',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au74932',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_74932',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au75063',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_75063',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au76016',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_76016',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au76017',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_76017',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au77525',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_77525',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au77526',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_77526',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au78702',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_78702',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au79443',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_79443',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au79444',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_79444',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au79445',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_79445',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au79446',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_79446',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au79447',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_79447',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au79448',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_79448',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au79794',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_79794',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au79795',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_79795',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au80459',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_80459',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au80460',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_80460',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au80461',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_80461',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au80462',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_80462',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au80463',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_80463',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au80611',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_80611',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au81268',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_81268',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au81269',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_81269',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au81462',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_81462',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au81463',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_81463',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au81464',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_81464',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au81465',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_81465',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au81466',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_81466',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au81467',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_81467',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au81468',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_81468',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au81469',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_81469',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au81857',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_81857',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au81858',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_81858',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au82998',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_82998',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au82999',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_82999',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au83073',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_83073',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au83074',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_83074',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au83075',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_83075',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au83140',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_83140',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au83811',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_83811',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au84499',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_84499',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au85191',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_85191',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au85192',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_85192',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au85193',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_85193',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au85194',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_85194',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au85195',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_85195',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au85768',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_85768',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Au85769',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'au_85769',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz10479',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_10479',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz10481',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_10481',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz10482',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_10482',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz10484',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_10484',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz10533',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_10533',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz10642',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_10642',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz10662',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_10662',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz10663',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_10663',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz10667',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_10667',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz11028',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_11028',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz11050',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_11050',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz11075',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_11075',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz11178',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_11178',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz11382',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_11382',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz11430',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_11430',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz11440',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_11440',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz11463',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_11463',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz11465',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_11465',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz11466',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_11466',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz11467',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_11467',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz11468',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_11468',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz11469',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_11469',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12050',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12050',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12051',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12051',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12054',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12054',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12105',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12105',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12106',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12106',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12107',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12107',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12108',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12108',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12118',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12118',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12119',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12119',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12120',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12120',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12121',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12121',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12123',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12123',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12134',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12134',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12136',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12136',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12137',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12137',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12138',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12138',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12139',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12139',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12140',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12140',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12141',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12141',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12474',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12474',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12510',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12510',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz12956',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_12956',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz13100',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_13100',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz13101',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_13101',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz6404',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_6404',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz6405',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_6405',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz6407',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_6407',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz6410',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_6410',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz6411',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_6411',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz6413',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_6413',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz6414',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_6414',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz6419',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_6419',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz6420',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_6420',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8746',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8746',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8747',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8747',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8748',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8748',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8749',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8749',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8750',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8750',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8752',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8752',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8756',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8756',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8758',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8758',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8759',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8759',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8760',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8760',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8763',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8763',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8764',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8764',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8765',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8765',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8766',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8766',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz8767',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_8767',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz9366',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_9366',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz9636',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_9636',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz9658',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_9658',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nz9815',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.IntegerField(unique=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nz_9815',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductAu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_au',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductNz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_nz',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
