# Generated by Django 2.0.3 on 2018-03-16 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('coutry', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=30)),
                ('retailprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('url', models.URLField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hist_price.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='Item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hist_price.Item'),
        ),
    ]
