# Generated by Django 2.0.3 on 2018-03-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hist_price', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='coutry',
            new_name='country',
        ),
    ]
