# Generated by Django 2.0.3 on 2018-03-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hist_price', '0002_auto_20180317_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='logo',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
