# Generated by Django 2.0.3 on 2018-03-28 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hist_price', '0003_auto_20180317_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='PriceHistory',
        ),
    ]
